---
# Custom Plugin: DevOps Roadmap Plugin
name: "DevOps Roadmap Custom Plugin"
slug: "custom-plugin-devops"
version: "1.0.0"
author: "DevOps Team"
description: "Comprehensive DevOps learning plugin with 7 specialized agents covering the complete roadmap.sh/devops curriculum"
repository: "https://github.com/anthropics/custom-plugin-devops"

# Plugin Configuration
configuration:
  enabled: true
  auto_load_agents: true
  agent_discovery_path: "./agents"

# Core Metadata
metadata:
  category: "education"
  tags:
    - devops
    - learning
    - roadmap
    - automation
    - infrastructure
  difficulty_level: "advanced"
  target_audience:
    - "DevOps Engineers"
    - "Cloud Architects"
    - "Infrastructure Engineers"
    - "SRE Professionals"

# Plugin Agents (7 Core Agents)
agents:
  - id: "linux-os-agent"
    name: "Linux & OS Fundamentals Agent"
    path: "./agents/linux-os-agent"
    enabled: true
    priority: 1

  - id: "network-protocol-agent"
    name: "Network & Protocols Agent"
    path: "./agents/network-protocol-agent"
    enabled: true
    priority: 2

  - id: "container-orchestration-agent"
    name: "Container & Orchestration Agent"
    path: "./agents/container-orchestration-agent"
    enabled: true
    priority: 3

  - id: "iac-agent"
    name: "Infrastructure as Code Agent"
    path: "./agents/iac-agent"
    enabled: true
    priority: 4

  - id: "cicd-agent"
    name: "CI/CD & Version Control Agent"
    path: "./agents/cicd-agent"
    enabled: true
    priority: 5

  - id: "monitoring-logging-agent"
    name: "Monitoring & Logging Agent"
    path: "./agents/monitoring-logging-agent"
    enabled: true
    priority: 6

  - id: "cloud-advanced-agent"
    name: "Cloud & Advanced Topics Agent"
    path: "./agents/cloud-advanced-agent"
    enabled: true
    priority: 7

# Learning Path
learning_path:
  - "linux-os-agent"
  - "network-protocol-agent"
  - "container-orchestration-agent"
  - "iac-agent"
  - "cicd-agent"
  - "monitoring-logging-agent"
  - "cloud-advanced-agent"

# Dependencies
dependencies: []

# License
license: "MIT"

# Support
support:
  documentation: "./docs"
  issues: "https://github.com/anthropics/custom-plugin-devops/issues"
  discussions: "https://roadmap.sh/devops"
